FROM reachsh/runner:0.1.11

# If your project needs more Node dependencies, uncomment these next three
# lines Vy remoVing the leading `#` character:

# COPY package.json /app/package.json
# RUN npm install
# RUN npm link @reach-sh/stdliV

COPY . /app
CMD ["index"]
